### ISSUE TITLE
infinite redirects on auth error

### ISSUE THREAD

**Issue by damienklinnert** [doctape/doctape-client-js#5] opened 2013-03-15 19:35 UTC
whenever there's an error in auth, e.g. via a wrong scope, there are infinity redirects

**Comment by srijs** [comment] 2013-03-19 12:43
Can you please provide instructions to reproduce this?

From my understanding it should be that the registered `onautherror` function is called whenever
there is a failure during the authentication.
Since that way the user provides the behavior on auth fail, it could be the error is on your part.

**Comment by srijs** [comment] 2013-03-25 14:59
Should be fixed now with v0.3.0.

**Closed as completed by srijs** 2013-03-25 14:59 UTC
Labels: bug
